const GET_CATEGORIES = "GET_CATEGORIES";
const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";

const PUT_CATEGORY = "PUT_CATEGORY";
const POST_CATEGORY = "POST_CATEGORY";
const PUT_CATEGORY_SUCCESS = "PUT_CATEGORY_SUCCESS"
const POST_CATEGORY_SUCCESS = "POST_CATEGORY_SUCCESS"

const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";

export {
    GET_CATEGORIES, 
    GET_CATEGORIES_SUCCESS, 
    PUT_CATEGORY,
    POST_CATEGORY,
    GET_ALL_CATEGORIES,
    GET_ALL_CATEGORIES_SUCCESS,
    PUT_CATEGORY_SUCCESS,
    POST_CATEGORY_SUCCESS
}