const HIDE_COLUMN_AUTHOR = "HIDE_COLUMN_AUTHOR";
const DISPLAY_COLUMN_AUTHOR = "DISPLAY_COLUMN_AUTHOR";
const GET_INFO_ACCOUNT = "GET_INFO_ACCOUNT";
const GET_INFO_ACCOUNT_SUCCESS = "GET_INFO_ACCOUNT_SUCCESS";
const LOADING = "LOADING";
const LOAD_SUCCESS = "LOAD_SUCCESS";

export {
  HIDE_COLUMN_AUTHOR,
  DISPLAY_COLUMN_AUTHOR,
  LOADING,
  LOAD_SUCCESS,
  GET_INFO_ACCOUNT,
  GET_INFO_ACCOUNT_SUCCESS,
};
