const GET_COMMENT = "GET_COMMENT";
const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";

const POST_COMMENT = "POST_COMMENT";
const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";

const GET_HISTORY = "GET_HISTORY";
const GET_HISTORY_SUCCESS = "GET_HISTORY_SUCCESS";

export {
  GET_COMMENT,
  GET_COMMENT_SUCCESS,
  POST_COMMENT,
  POST_COMMENT_SUCCESS,
  GET_HISTORY,
  GET_HISTORY_SUCCESS
};

