const GET_DEPARTMENTS = "GET_DEPARTMENTS";
const GET_DEPARTMENTS_SUCCESS = "GET_DEPARTMENTS_SUCCESS";

const PUT_DEPARTMENT = "PUT_DEPARTMENT";
const PUT_DEPARTMENT_SUCCESS = "PUT_DEPARTMENT_SUCCESS";

const POST_DEPARTMENT = "POST_DEPARTMENT";
const POST_DEPARTMENT_SUCCESS = "POST_DEPARTMENT_SUCCESS";

const GET_ALL_DEPARTMENT = 'GET_ALL_DEPARTMENT';
const GET_ALL_DEPARTMENT_SUCCESS = 'GET_ALL_DEPARTMENT_SUCCESS';

export {
    GET_DEPARTMENTS,
    GET_DEPARTMENTS_SUCCESS,
    PUT_DEPARTMENT,
    POST_DEPARTMENT,
    GET_ALL_DEPARTMENT,
    GET_ALL_DEPARTMENT_SUCCESS,
    PUT_DEPARTMENT_SUCCESS,
    POST_DEPARTMENT_SUCCESS
};
