const POST_EMAIL = 'POST_EMAIL';
const POST_EMAIL_SUCCESS = "POST_EMAIL_SUCCESS";
const POST_EMAIL_GOOGLE = "POST_EMAIL_GOOGLE";
const POST_EMAIL_GOOGLE_SUCCESS = "POST_EMAIL_GOOGLE_SUCCESS";
const LOGOUT = "LOGOUT";

export { POST_EMAIL, POST_EMAIL_SUCCESS, POST_EMAIL_GOOGLE, POST_EMAIL_GOOGLE_SUCCESS, LOGOUT }