const GET_REQUESTS = "GET_REQUESTS";
const GET_REQUESTS_SUCCESS = "GET_REQUESTS_SUCCESS";

const PUT_REQUEST = "PUT_REQUEST";
const PUT_REQUEST_SUCCESS = "PUT_REQUEST_SUCCESS";


const POST_REQUEST = "POST_REQUEST";
const POST_REQUEST_SUCCESS = 'POST_REQUEST_SUCCESS'

const DELETE_REQUEST = "DELETE_REQUEST";
const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS"
const GET_TOTAL_REQUESTS = "GET_TOTAL_REQUESTS";
const GET_TOTAL_REQUESTS_SUCCESS = "GET_TOTAL_REQUESTS_SUCCESS";

export {
    GET_REQUESTS,
    GET_REQUESTS_SUCCESS,
    PUT_REQUEST,
    POST_REQUEST,
    PUT_REQUEST_SUCCESS,
    POST_REQUEST_SUCCESS,
    DELETE_REQUEST_SUCCESS,
    DELETE_REQUEST,
    GET_TOTAL_REQUESTS,
    GET_TOTAL_REQUESTS_SUCCESS
}