const GET_USERS = "GET_USERS";
const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";

const GET_ALL_ADMIN = "GET_ALL_ADMIN";
const GET_ALL_ADMIN_SUCCESS = "GET_ALL_ADMIN_SUCCESS";

const GET_ALL_AUTHOR = "GET_ALL_AUTHOR";
const GET_ALL_AUTHOR_SUCCESS = "GET_ALL_AUTHOR_SUCCESS";

const GET_ROLES = "GET_ROLES";
const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";

const PUT_USER = "PUT_USER";
const PUT_USER_SUCCESS = "PUT_USER_SUCCESS";

const POST_USER = "POST_USER";
const POST_USER_SUCCESS = "POST_USER_SUCCESS"

export {
    GET_USERS,
    GET_USERS_SUCCESS,
    GET_ROLES,
    GET_ROLES_SUCCESS,
    PUT_USER,
    POST_USER,
    GET_ALL_ADMIN,
    GET_ALL_ADMIN_SUCCESS,
    PUT_USER_SUCCESS,
    POST_USER_SUCCESS,
    GET_ALL_AUTHOR,
    GET_ALL_AUTHOR_SUCCESS
};
